name: Exchange GitHub JWTs for VeraId credentials
description:
  Exchange GitHub JWTs for VeraId credentials via an instance of VeraId
  Authority
author: Relaycorp

branding:
  icon: check
  color: green

inputs:
  exchange-url:
    description:
      The URL to the credential exchange endpoint on an instance of VeraId
      Authority
    required: true

outputs:
  credential:
    description: The VeraId credential (Base64-encoded)
  type:
    description:
      The type of the VeraId credential (e.g.
      "application/vnd.veraid.signature-bundle")

runs:
  using: node20
  main: dist/index.js
